#!/bin/bash


# -------- Color names --------
# Reset
Color_Off=`echo -e '\e[0m'`       # Text Reset

# Regular Colors
Black=`echo -e '\e[0;30m'`        # Black
Red=`echo -e '\e[0;31m'`          # Red
Green=`echo -e '\e[0;32m'`        # Green
Yellow=`echo -e '\e[0;33m'`       # Yellow
Blue=`echo -e '\e[0;34m'`         # Blue
Purple=`echo -e '\e[0;35m'`       # Purple
Cyan=`echo -e '\e[0;36m'`         # Cyan
White=`echo -e '\e[0;37m'`        # White

# Bold
BBlack=`echo -e '\e[1;30m'`       # Black
BRed=`echo -e '\e[1;31m'`         # Red
BGreen=`echo -e '\e[1;32m'`       # Green
BYellow=`echo -e '\e[1;33m'`      # Yellow
BBlue=`echo -e '\e[1;34m'`        # Blue
BPurple=`echo -e '\e[1;35m'`      # Purple
BCyan=`echo -e '\e[1;36m'`        # Cyan
BWhite=`echo -e '\e[1;37m'`       # White

# Underline
UBlack=`echo -e '\e[4;30m'`       # Black
URed=`echo -e '\e[4;31m'`         # Red
UGreen=`echo -e '\e[4;32m'`       # Green
UYellow=`echo -e '\e[4;33m'`      # Yellow
UBlue=`echo -e '\e[4;34m'`        # Blue
UPurple=`echo -e '\e[4;35m'`      # Purple
UCyan=`echo -e '\e[4;36m'`        # Cyan
UWhite=`echo -e '\e[4;37m'`       # White

# Background
On_Black=`echo -e '\e[40m'`       # Black
On_Red=`echo -e '\e[41m'`         # Red
On_Green=`echo -e '\e[42m'`       # Green
On_Yellow=`echo -e '\e[43m'`      # Yellow
On_Blue=`echo -e '\e[44m'`        # Blue
On_Purple=`echo -e '\e[45m'`      # Purple
On_Cyan=`echo -e '\e[46m'`        # Cyan
On_White=`echo -e '\e[47m'`       # White

# High Intensty
IBlack=`echo -e '\e[0;90m'`       # Black
IRed=`echo -e '\e[0;91m'`         # Red
IGreen=`echo -e '\e[0;92m'`       # Green
IYellow=`echo -e '\e[0;93m'`      # Yellow
IBlue=`echo -e '\e[0;94m'`        # Blue
IPurple=`echo -e '\e[0;95m'`      # Purple
ICyan=`echo -e '\e[0;96m'`        # Cyan
IWhite=`echo -e '\e[0;97m'`       # White

# Bold High Intensty
BIBlack=`echo -e '\e[1;90m'`      # Black
BIRed=`echo -e '\e[1;91m'`        # Red
BIGreen=`echo -e '\e[1;92m'`      # Green
BIYellow=`echo -e '\e[1;93m'`     # Yellow
BIBlue=`echo -e '\e[1;94m'`       # Blue
BIPurple=`echo -e '\e[1;95m'`     # Purple
BICyan=`echo -e '\e[1;96m'`       # Cyan
BIWhite=`echo -e '\e[1;97m'`      # White

# High Intensty backgrounds
On_IBlack=`echo -e '\e[0;100m'`   # Black
On_IRed=`echo -e '\e[0;101m'`     # Red
On_IGreen=`echo -e '\e[0;102m'`   # Green
On_IYellow=`echo -e '\e[0;103m'`  # Yellow
On_IBlue=`echo -e '\e[0;104m'`    # Blue
On_IPurple=`echo -e '\e[10;95m'`  # Purple
On_ICyan=`echo -e '\e[0;106m'`    # Cyan
On_IWhite=`echo -e '\e[0;107m'`   # White

# -------- Functions --------

print_usage() {
    echo "Highlights parts of the text."
    echo "Usage: $0 -h" 
    echo "       $0 [options] color pattern"
    echo "Options:"
    echo "    -h        This help message."
    echo "    -i        Case insensitive pattern."
    echo "    -l        Highlight the whole line containing the pattern."
    echo "    -r        Interpret the pattern as extended regular expression."
    echo
    echo "Color format: [Flags]ColorName"
    echo "    where ColorName = Black|Red|Greem|Yellow|Blue|Purple|Cyan|White"
    echo "      Flags = B|I|U|On_|BI|On_I"
    echo "        B = bold  I = High intensity  U = Underline  On_ = Background"
}

# -------- Main body --------

flags=g
args=-u
parprefix='\'
prefix=
postfix=
matchindex=1
while getopts ":hilr" Option; do
    case $Option in
        h) 
	    print_usage
	    exit
	    ;;
	i)
	    flags=${flags}I
	    ;;
	l)
	    prefix='^.*'
	    postfix='.*$'
	    ;;
	r)
	    args="$args -r"
	    parprefix=
	    ;;
    esac
done

shift $(($OPTIND - 1))


coloridx=$1
exp=$2
color=${!coloridx}
openpar="$parprefix("
closepar="$parprefix)"

if [ -z $color ]; then
    echo "Invalid color."
    exit 1
fi

match="${openpar}${prefix}${openpar}${exp}${closepar}${postfix}${closepar}"
xpr="s/${match}/${color}\\${matchindex}${Color_Off}/${flags}"
#echo "$xpr"
sed $args -e "$xpr"

