#!/bin/bash

if echo "$0" | grep -q /; then
	hl="$(dirname "$0")/hl"
else
	hl="$(which hl)"
fi

if [ ! -x "$hl" ]; then
    echo "No hl script."
    exit 1
fi

filename="$1"
if [ -z "$filename" ]; then
    filename=/dev/stdin
fi
cat "$filename" | "$hl" Red '[.+]' | "$hl" IYellow '[oO]' | "$hl" IBlue 'Y' | "$hl" IGreen 'X' | less -R
