#!/bin/bash

if ! which hl >/dev/null; then
    echo "No hl script."
    exit 1
fi

filename="$1"
if [ -z "$filename" ]; then
    filename=/dev/stdin
fi
cat "$filename" | hl Red '[.+]' | hl IYellow '[oO]' | hl IBlue 'Y' | hl IGreen 'X' | less -R
