#!/bin/bash

input="$1"
output="$2"

shift 2

rm -f "$output"

while read file; do
    if [ -z "$file" ]; then
        continue
    fi

    echo
    echo "$file"
    echo "$file" >>$"$output"
	filePath="$(dirname $input)/$file"
    echo "----------------------------------" >>"$output"
    "$@" "$filePath" 2>&1 | tee >(egrep '^(Expanded nodes:|Length of solution:|Processor Time:|^Status|calculateReachable called|Solution)' >>"$output")
	echo "Return code: $?" >>"$output"
    echo "----------------------------------" >>"$output"
    echo >>"$output"
done <"$input"

