#!/bin/bash

input="$1"
output="$2"

shift 2

if [ -e "$output" ]; then
	echo "Error: output file \"$output\" already exists" >&2
	exit 1
fi

while read file; do
    if [ -z "$file" ]; then
        continue
    fi

    echo
    echo "$file"
    echo "$file" >>$"$output"
	filePath="$(dirname $input)/$file"
    echo "----------------------------------" >>"$output"
    "$@" "$filePath" --output-format='Solution %quality%
Solution length:           %length%
Expanded nodes:            %expanded-nodes%
Status copied:             %status-copied%
Status moved:              %status-moved%
calculateReachable called: %calculate-reachable-called%
Chokepoint finding time:   %chokepoint-real-time% [%chokepoint-processor-time%]
Preprocessing time:        %iteration-real-time% [%iteration-processor-time%]
Total time:                %total-real-time% [%total-processor-time%]
' | tee -a "$output"
	echo "Return code: $?" >>"$output"
    echo "----------------------------------" >>"$output"
    echo >>"$output"
done <"$input"

