#!/bin/bash

input="$1"
output="$2"

shift 2

if [ -e "$output" ]; then
	echo "Error: output file \"$output\" already exists" >&2
	exit 1
fi

while read file; do
    if [ -z "$file" ]; then
        continue
    fi

    echo
    echo "$file"
    echo "$file" >>$"$output"
	filePath="$(dirname $input)/$file"
    echo "----------------------------------" >>"$output"
    "$@" "$filePath" 2>&1 | tee >(egrep '^(Expanded nodes:|Length of solution:|Processor Time:|Iteration.*time:|^Status|calculateReachable called|[sS]olution)|list size' >>"$output")
	echo "Return code: $?" >>"$output"
    echo "----------------------------------" >>"$output"
    echo >>"$output"
done <"$input"

